org: kartago
service: productos-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 10
  memorySize: 1024
  iam:
    role: arn:aws:iam::721114448578:role/LabRole

functions:
  crearProducto:
    handler: handler.crearProducto
    events:
      - http:
          path: /producto
          method: post
          cors: true

  obtenerProductos:
    handler: handler.obtenerProductos
    events:
      - http:
          path: /producto
          method: get
          cors: true

  buscarProductos:
    handler: handler.buscarProductos
    events:
      - http:
          path: /buscar
          method: get
          cors: true

  eliminarProducto:
    handler: handler.eliminarProducto
    events:
      - http:
          path: /producto/{id}
          method: delete
          cors: true
