org: kartago
service: productos-api

frameworkVersion: '^4'

provider:
  name: aws
  runtime: nodejs18.x
  iam: 
    role: arn:aws:iam::721114448578:role/LabRole
  region: us-east-1
  stage: dev
  timeout: 10

functions:
  crearProducto:
    handler: handler.crearProducto
    events:
      - httpApi:
          path: /producto
          method: post

  obtenerProductos:
    handler: handler.obtenerProductos
    events:
      - httpApi:
          path: /producto
          method: get

  buscarProducto:
    handler: handler.buscarProducto
    events:
      - httpApi:
          path: /buscar
          method: get

  eliminarProducto:
    handler: handler.eliminarProducto
    events:
      - httpApi:
          path: /producto/{id}
          method: delete
